name: docker-build-and-push-to-container-registry

on: 
  push:
    branches:    
      - main
      
jobs:
  build-and-push-to-ghcr:
    name: testing the sample workflow cicd
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
          echo "GHCR login success"
          
      - name: build and push docker image to GHCR
        run: |
          docker build -t nodeapp:xyzabcoooo .
          IMAGE_ID=ghcr.io/nodeapp:xyzabcoooo
          docker push $IMAGE_ID
          echo "Docker Image build success"
          
      
